### ISSUE TITLE
Automate the `Initiate chat space with a bot` task

### ISSUE THREAD

**Issue by PROxZIMA** [googleworkspace/hangouts-chat-samples#111]
If I'm not wrong then as of now an user has to manually find the bot and initiate a chat space. So is there a way using which we can initiate a chat space with the bot when an user clicks on some external link?

My use case is simple. Verifying a user using OAuth2 then redirecting them to initiate the chat space with my bot. Former part is easy to implement and well documented but I want to automate the latter part. If there's any way to implement it then I'd love to know it.

Thanks

**Comment by sqrrrl** [comment]
It's not currently possible for a bot to initiate a DM with a user, nor create a deep link to do that. It's something under consideration, though there aren't any hard plans at the moment.

That said, once a user initiates a DM with a bot, the space ID is stable and you can persist the user/space mapping and use it to send updates to the user later on.
