### ISSUE TITLE
about google chat Card messages 

### ISSUE THREAD

**Issue by diaowenyang** [googleworkspace/hangouts-chat-samples#112]
Our company is now using google chat as an internal IM tool.
Now we want to add some OA functions to it, such as user initiating some application messages.
We need to render a form inside google chat Card messages,
let the user input some information, and then click a link to submit the content of the form to us.

https://developers.google.com/chat/api/guides/message-formats/cards#card_text_formatting

I refer to the url example above, the example in it doesn't meet the above requirement.
Can google chat card messages achieve the above requirement？

Thank you very much.

**Comment by sqrrrl** [comment]
Possibly. Forms are now supported via dialogs initiated with slash commands. See https://developers.google.com/chat/how-tos/bot-dialogs for more information.

Cards as part of messages in a space (DM, multi-user space) do not yet support form inputs.
