### ISSUE TITLE
After User click Button on Card messages,how to change the button color

### ISSUE THREAD

**Issue by diaowenyang** [googleworkspace/hangouts-chat-samples#113]
![aaaa](https://user-images.githubusercontent.com/18416111/142571416-a529b3bc-8863-43c2-9515-eb6141e8a8ec.jpeg)

When the user clicks the button, I want the button to be grayed out to let the user know that the message has been processed by him. Is it possible to achieve this?

Thank you very much.

**Comment by sqrrrl** [comment]
It's currently not possible to do this. At best you can rerender/update the card with the button removed to prevent the user from clicking again.

Is this in a DM or a multi user space? Keep in mind that when more than 1 user is in the space, there's state of the message is shared across all users. There's no mechanism to display different versions of the card to different users depending on how they interacted.

**Comment by diaowenyang** [comment]
Thank you very much.
