### ISSUE TITLE
Google Chat Input form inside card and Carousel Support

### ISSUE THREAD

**Issue by kiranbudati** [googleworkspace/hangouts-chat-samples#90]
I am working on google chat bots, i was trying to embedded input form into card just like adaptive cards like this https://adaptivecards.io/samples/InputForm.html, as per the google chat api documentation input fields are not supported, is there any alternative way to add input form to card.

Also i was trying to add carousel which bot needs to send.

**Comment by diaowenyang** [comment]
@kiranbudati 
I also trying to embedded input form into card, did you find a solution please?
Thank you very much.

**Comment by diaowenyang** [comment]
I solved this problem with the following method.
https://developers.googleblog.com/2021/06/add-dialogs-and-slash-commands-to-your-google-workspace-chat-bots.html

**Comment by sqrrrl** [comment]
+1, forms are currently only available via dialogs.

Closing issue since it looks like a general question, not the samples contained in this repository. We recommend asking such using the resources in the [support guide.](https://developers.google.com/chat/support)
